### ISSUE TITLE
What is the Participants Limit 

### ISSUE THREAD

**Issue by harivyas35** [meething/meething#228]

**Comment by lmangani** [comment]
There's not set limit other than technical limitations of either client/server side components. In P2P/MESH mode this is up to the clients and you can expect 5-6 participants before overloading each client due to the multiple streaming - the advantage is being serverless. In SFU mode the limit is moved to the server forwarder instead, and should support 50-100 participants (not on the client)

I hope this helps!

**Comment by harivyas35** [comment]
If i dont select P2P (i.e mesh =true ),while joining the meeting, is it true SFU (i mena 50 -100 participants can join my room by not selecting P2P option

**Comment by lmangani** [comment]
Yes - that's intended with your own setup, including the meething-mediasoup sfu component on your server. The hosted demo might have different results.
