### ISSUE TITLE
ERR_CONNECTION_CLOSED on https://web.meething.space

### ISSUE THREAD

**Issue by stritti** [meething/meething#230]
**Describe the bug**
If I click the project link https://web.meething.space which is next to the description (see screenshot) I always get always `ERR_CONNECTION_CLOSEDD`. 
Using insecure `http` protocol, it is forwarded successfully to https://meething.github.io/meething-webpage/index.html

**To Reproduce**
1. Go to 'https://github.com/meething/meething'
2. Click on 'https://web.meething.space/'

**Expected behavior**
Forward to https://meething.github.io/meething-webpage/index.html
Maybe just remove the `s` from `https://...` to solve this issue ...

**Screenshots**
![image](https://user-images.githubusercontent.com/184547/84884724-6128d080-b092-11ea-96ab-6dad1a2e2bb8.png)

**Comment by Tollan02** [comment]
If you enjoy reading Action-Adventure, Science-Fiction or Thrillers, check out my Amazon page;
T.I.Wade

 
T.I.Wade


     On Wednesday, June 17, 2020, 06:04:12 AM EDT, Stephan Strittmatter <notifications@github.com> wrote:  
 
 


Describe the bug
If I click the project link https://web.meething.space which is next to the description (see screenshot) I always get always ERR_CONNECTION_CLOSEDD.
Using insecure http protocol, it is forwarded successfully to https://meething.github.io/meething-webpage/index.html

To Reproduce
Steps to reproduce the behavior:
   
   - Go to 'https://github.com/meething/meething'
   - Click on 'https://web.meething.space/'
   - See error

Expected behavior
Forward to https://meething.github.io/meething-webpage/index.html
Maybe just remove the s from https://... to solve this issue ...

Screenshots

**Comment by lmangani** [comment]
Thanks for the reminder - fixed with the correct URL
