### ISSUE TITLE
Old videos/participants not removing from UI when calling between Chrome and Firefox.

### ISSUE THREAD

**Issue by Tollan02** [meething/meething#84]
**Describe the bug**
NB; Tests were done on same LAN.

**To Reproduce**
1. Open multiple instances using Chrome and Firefox (2+ instances EACH) with half on Chrome and half on Firefox.
2. Close some of the instances

**Expected behavior**
When an instance/user leaves, user ID and video frame should disappear on other instances.

**Screenshots**
![image](https://user-images.githubusercontent.com/7888261/80421076-e28d8f00-88a9-11ea-85cb-36af279d43ac.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: chrome to firefox
 - Version: latest

**Additional context**
- Link you used? REDACTED
- Branch you used? (Such as fix_audio) Master/hepic

**Metric**
- Perfomance / Benchmarking
- Latency
- [ ] Cross site scripting

**Comment by lmangani** [comment]
@Tollan02 thanks for the report!

Those objects appear to have no height, suggesting the video was never connected to them, rather than the user leaving - or perhaps they rejoined? We need a step by step procedure we can replicate OR as you reproduce this issue on your LAN please paste the browser console logs around the time and before the issue is manifested, to see what action has failed.

**Comment by lmangani** [comment]
This should be fixed. Please reopen if you notice the same issue. Thanks!
